name: Flatpak Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flatpak-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak-builder

      - name: Setup Flatpak
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.gnome.Platform//48 org.gnome.Sdk//48 org.freedesktop.Sdk.Extension.node24//24.8

      - name: Build Flatpak
        run: |
          flatpak-builder --force-clean build io.github.tduarte.Pipoca.json

      - name: Test Flatpak
        run: |
          flatpak-builder --run build io.github.tduarte.Pipoca.json pipoca --help || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-build
          path: build/
